ktor:
  deployment:
    port: ${PORT:8080}
    host: "0.0.0.0"

  application:
    modules:
      - com.bike.ApplicationKt.module

database:
  url: ${DB_URL}
  driver: "org.postgresql.Driver"
  user: ${DB_USER}
  password: ${DB_PASSWORD}
